// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA58fgeOuPd-xVZxBTI-rDbvfQp8kLeVI8',
    appId: '1:501093866393:web:67c61c633b58e072b79108',
    messagingSenderId: '501093866393',
    projectId: 'budgetapp-78598',
    authDomain: 'budgetapp-78598.firebaseapp.com',
    storageBucket: 'budgetapp-78598.appspot.com',
    measurementId: 'G-57Y6WX47C8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhry33rvjMSkOuDAIdV_ka_nSGxvnkk2Y',
    appId: '1:501093866393:android:834fcadd6d0b25beb79108',
    messagingSenderId: '501093866393',
    projectId: 'budgetapp-78598',
    storageBucket: 'budgetapp-78598.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCimlUMLc1vy7qZrUFWinlpwC1HOy5SYoI',
    appId: '1:501093866393:ios:91fb5756cb6df70ab79108',
    messagingSenderId: '501093866393',
    projectId: 'budgetapp-78598',
    storageBucket: 'budgetapp-78598.appspot.com',
    iosBundleId: 'com.example.flutterBudgetApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCimlUMLc1vy7qZrUFWinlpwC1HOy5SYoI',
    appId: '1:501093866393:ios:f5852dc74533749fb79108',
    messagingSenderId: '501093866393',
    projectId: 'budgetapp-78598',
    storageBucket: 'budgetapp-78598.appspot.com',
    iosBundleId: 'com.example.flutterBudgetApp.RunnerTests',
  );
}
